# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432" # Maps host port 8080 to container port 80
    volumes:
      ##Change to a better local path 
    - /home/vaibh/Documents/ECE-464-Databases/final_project/database/pdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
